[package]
name = "rot"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.3"
once_cell = "1.17"

[dependencies.tokio]
version = "1.0"
features = ["net", "io-util", "signal", "sync", "time", "rt", "macros"]
